[package]
name = "teleora"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pest = "2.6.0"
pest_derive = "2.6.0"
pest_ascii_tree = "0.1.0" # debug (rmove)
lazy_static = "*"